package localhost;

// Generated 27/09/2011 10:38:52 by Hibernate Tools 3.4.0.CR1

import java.util.Collection;
import java.util.Date;

/**
 * Usuario generated by hbm2java
 */
public class Usuario extends ObjetoPersistente implements java.io.Serializable {

	private Date datanascimento;
	private String email;
	private String login;
	private String nome;
	private String senha;
	private int sexo;
	private String telefone;
	private Long id;
	private Collection<Papel> papeis;

	public Collection<Papel> getPapeis() {
		return papeis;
	}

	public void setPapeis(Collection<Papel> papeis) {
		this.papeis = papeis;
	}

	public Long getId() {
		return id;
	}
	
	public void setId(Long id) {
		this.id = id;
	}

	public Usuario() {
	}

	public Usuario(Long id, Date datanascimento, String login, String nome,
			String senha, int sexo, String telefone) {
		setId(id);
		this.datanascimento = datanascimento;
		this.login = login;
		this.nome = nome;
		this.senha = senha;
		this.sexo = sexo;
		this.telefone = telefone;
	}

	public Usuario(Long id, Long versao, Date datanascimento, String email,
			String login, String nome, String senha, int sexo, String telefone) {
		setId(id);
		setVersao(versao);
		this.datanascimento = datanascimento;
		this.email = email;
		this.login = login;
		this.nome = nome;
		this.senha = senha;
		this.sexo = sexo;
		this.telefone = telefone;
	}

	public Date getDatanascimento() {
		return this.datanascimento;
	}

	public void setDatanascimento(Date datanascimento) {
		this.datanascimento = datanascimento;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getSenha() {
		return this.senha;
	}

	public void setSenha(String senha) {
		this.senha = senha;
	}

	public int getSexo() {
		return this.sexo;
	}

	public void setSexo(int sexo) {
		this.sexo = sexo;
	}

	public String getTelefone() {
		return this.telefone;
	}

	public void setTelefone(String telefone) {
		this.telefone = telefone;
	}

}
