package localhost;

// Generated 27/09/2011 12:33:46 by Hibernate Tools 3.4.0.CR1

/**
 * Ocorrencia generated by hbm2java
 */
public class Ocorrencia implements java.io.Serializable {

	private Long id;
	private Long versao;
	private Long codigo;
	private Chamado chamado;

	public Ocorrencia() {
	}

	public Ocorrencia(Long id, Long codigo) {
		this.id = id;
		this.codigo = codigo;
	}

	public Ocorrencia(Long id, Long versao, Long codigo) {
		this.id = id;
		this.versao = versao;
		this.codigo = codigo;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getVersao() {
		return this.versao;
	}

	public void setVersao(Long versao) {
		this.versao = versao;
	}

	public long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(long codigo) {
		this.codigo = codigo;
	}

	public Chamado getChamado() {
		return chamado;
	}

	public void setChamado(Chamado chamado) {
		this.chamado = chamado;
	}

}
